server:
  error:
    include-message: always
  forward-headers-strategy: framework
  port: 18182
  servlet:
    context-path: /cypher-text

spring:
  application:
    name: service
  jackson:
    deserialization:
      accept-float-as-int: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
